server:
  port: 8081

spring:
  application:
    name: agent-data-manager
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/agent_data?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql

mybatis:
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
